// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/topic/BrokerTopicConfigWrapper.proto

package com.yimq.common.topic;

public final class BrokerTopicConfigWrapperProto {
  private BrokerTopicConfigWrapperProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BrokerTopicConfigWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yimq.common.protobuf.topic.BrokerTopicConfigWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */
    int getBrokerTopicConfigMapCount();
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */
    boolean containsBrokerTopicConfigMap(
        java.lang.String key);
    /**
     * Use {@link #getBrokerTopicConfigMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>
    getBrokerTopicConfigMap();
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */
    java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>
    getBrokerTopicConfigMapMap();
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */

    com.yimq.common.topic.TopicConfigProto.TopicConfig getBrokerTopicConfigMapOrDefault(
        java.lang.String key,
        com.yimq.common.topic.TopicConfigProto.TopicConfig defaultValue);
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */

    com.yimq.common.topic.TopicConfigProto.TopicConfig getBrokerTopicConfigMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.yimq.common.protobuf.topic.BrokerTopicConfigWrapper}
   */
  public  static final class BrokerTopicConfigWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yimq.common.protobuf.topic.BrokerTopicConfigWrapper)
      BrokerTopicConfigWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BrokerTopicConfigWrapper.newBuilder() to construct.
    private BrokerTopicConfigWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BrokerTopicConfigWrapper() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BrokerTopicConfigWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                brokerTopicConfigMap_ = com.google.protobuf.MapField.newMapField(
                    BrokerTopicConfigMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>
              brokerTopicConfigMap__ = input.readMessage(
                  BrokerTopicConfigMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              brokerTopicConfigMap_.getMutableMap().put(
                  brokerTopicConfigMap__.getKey(), brokerTopicConfigMap__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yimq.common.topic.BrokerTopicConfigWrapperProto.internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetBrokerTopicConfigMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yimq.common.topic.BrokerTopicConfigWrapperProto.internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper.class, com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper.Builder.class);
    }

    public static final int BROKERTOPICCONFIGMAP_FIELD_NUMBER = 1;
    private static final class BrokerTopicConfigMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>newDefaultInstance(
                  com.yimq.common.topic.BrokerTopicConfigWrapperProto.internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_BrokerTopicConfigMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.yimq.common.topic.TopicConfigProto.TopicConfig.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> brokerTopicConfigMap_;
    private com.google.protobuf.MapField<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>
    internalGetBrokerTopicConfigMap() {
      if (brokerTopicConfigMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BrokerTopicConfigMapDefaultEntryHolder.defaultEntry);
      }
      return brokerTopicConfigMap_;
    }

    public int getBrokerTopicConfigMapCount() {
      return internalGetBrokerTopicConfigMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */

    public boolean containsBrokerTopicConfigMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetBrokerTopicConfigMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBrokerTopicConfigMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> getBrokerTopicConfigMap() {
      return getBrokerTopicConfigMapMap();
    }
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */

    public java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> getBrokerTopicConfigMapMap() {
      return internalGetBrokerTopicConfigMap().getMap();
    }
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */

    public com.yimq.common.topic.TopicConfigProto.TopicConfig getBrokerTopicConfigMapOrDefault(
        java.lang.String key,
        com.yimq.common.topic.TopicConfigProto.TopicConfig defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> map =
          internalGetBrokerTopicConfigMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
     */

    public com.yimq.common.topic.TopicConfigProto.TopicConfig getBrokerTopicConfigMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> map =
          internalGetBrokerTopicConfigMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetBrokerTopicConfigMap(),
          BrokerTopicConfigMapDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> entry
           : internalGetBrokerTopicConfigMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>
        brokerTopicConfigMap__ = BrokerTopicConfigMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, brokerTopicConfigMap__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper)) {
        return super.equals(obj);
      }
      com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper other = (com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper) obj;

      boolean result = true;
      result = result && internalGetBrokerTopicConfigMap().equals(
          other.internalGetBrokerTopicConfigMap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetBrokerTopicConfigMap().getMap().isEmpty()) {
        hash = (37 * hash) + BROKERTOPICCONFIGMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetBrokerTopicConfigMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yimq.common.protobuf.topic.BrokerTopicConfigWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yimq.common.protobuf.topic.BrokerTopicConfigWrapper)
        com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yimq.common.topic.BrokerTopicConfigWrapperProto.internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetBrokerTopicConfigMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableBrokerTopicConfigMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yimq.common.topic.BrokerTopicConfigWrapperProto.internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper.class, com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper.Builder.class);
      }

      // Construct using com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableBrokerTopicConfigMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yimq.common.topic.BrokerTopicConfigWrapperProto.internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_descriptor;
      }

      public com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper getDefaultInstanceForType() {
        return com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper.getDefaultInstance();
      }

      public com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper build() {
        com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper buildPartial() {
        com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper result = new com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper(this);
        int from_bitField0_ = bitField0_;
        result.brokerTopicConfigMap_ = internalGetBrokerTopicConfigMap();
        result.brokerTopicConfigMap_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper) {
          return mergeFrom((com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper other) {
        if (other == com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper.getDefaultInstance()) return this;
        internalGetMutableBrokerTopicConfigMap().mergeFrom(
            other.internalGetBrokerTopicConfigMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> brokerTopicConfigMap_;
      private com.google.protobuf.MapField<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>
      internalGetBrokerTopicConfigMap() {
        if (brokerTopicConfigMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              BrokerTopicConfigMapDefaultEntryHolder.defaultEntry);
        }
        return brokerTopicConfigMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>
      internalGetMutableBrokerTopicConfigMap() {
        onChanged();;
        if (brokerTopicConfigMap_ == null) {
          brokerTopicConfigMap_ = com.google.protobuf.MapField.newMapField(
              BrokerTopicConfigMapDefaultEntryHolder.defaultEntry);
        }
        if (!brokerTopicConfigMap_.isMutable()) {
          brokerTopicConfigMap_ = brokerTopicConfigMap_.copy();
        }
        return brokerTopicConfigMap_;
      }

      public int getBrokerTopicConfigMapCount() {
        return internalGetBrokerTopicConfigMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
       */

      public boolean containsBrokerTopicConfigMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetBrokerTopicConfigMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getBrokerTopicConfigMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> getBrokerTopicConfigMap() {
        return getBrokerTopicConfigMapMap();
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
       */

      public java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> getBrokerTopicConfigMapMap() {
        return internalGetBrokerTopicConfigMap().getMap();
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
       */

      public com.yimq.common.topic.TopicConfigProto.TopicConfig getBrokerTopicConfigMapOrDefault(
          java.lang.String key,
          com.yimq.common.topic.TopicConfigProto.TopicConfig defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> map =
            internalGetBrokerTopicConfigMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
       */

      public com.yimq.common.topic.TopicConfigProto.TopicConfig getBrokerTopicConfigMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> map =
            internalGetBrokerTopicConfigMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearBrokerTopicConfigMap() {
        internalGetMutableBrokerTopicConfigMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
       */

      public Builder removeBrokerTopicConfigMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableBrokerTopicConfigMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig>
      getMutableBrokerTopicConfigMap() {
        return internalGetMutableBrokerTopicConfigMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
       */
      public Builder putBrokerTopicConfigMap(
          java.lang.String key,
          com.yimq.common.topic.TopicConfigProto.TopicConfig value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableBrokerTopicConfigMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.topic.TopicConfig&gt; brokerTopicConfigMap = 1;</code>
       */

      public Builder putAllBrokerTopicConfigMap(
          java.util.Map<java.lang.String, com.yimq.common.topic.TopicConfigProto.TopicConfig> values) {
        internalGetMutableBrokerTopicConfigMap().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yimq.common.protobuf.topic.BrokerTopicConfigWrapper)
    }

    // @@protoc_insertion_point(class_scope:com.yimq.common.protobuf.topic.BrokerTopicConfigWrapper)
    private static final com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper();
    }

    public static com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BrokerTopicConfigWrapper>
        PARSER = new com.google.protobuf.AbstractParser<BrokerTopicConfigWrapper>() {
      public BrokerTopicConfigWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BrokerTopicConfigWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BrokerTopicConfigWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BrokerTopicConfigWrapper> getParserForType() {
      return PARSER;
    }

    public com.yimq.common.topic.BrokerTopicConfigWrapperProto.BrokerTopicConfigWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_BrokerTopicConfigMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_BrokerTopicConfigMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1src/protobuf/topic/BrokerTopicConfigWr" +
      "apper.proto\022\036com.yimq.common.protobuf.to" +
      "pic\032$src/protobuf/topic/TopicConfig.prot" +
      "o\"\366\001\n\030BrokerTopicConfigWrapper\022p\n\024broker" +
      "TopicConfigMap\030\001 \003(\0132R.com.yimq.common.p" +
      "rotobuf.topic.BrokerTopicConfigWrapper.B" +
      "rokerTopicConfigMapEntry\032h\n\031BrokerTopicC" +
      "onfigMapEntry\022\013\n\003key\030\001 \001(\t\022:\n\005value\030\002 \001(" +
      "\0132+.com.yimq.common.protobuf.topic.Topic" +
      "Config:\0028\001B6\n\025com.yimq.common.topicB\035Bro" +
      "kerTopicConfigWrapperProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yimq.common.topic.TopicConfigProto.getDescriptor(),
        }, assigner);
    internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_descriptor,
        new java.lang.String[] { "BrokerTopicConfigMap", });
    internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_BrokerTopicConfigMapEntry_descriptor =
      internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_descriptor.getNestedTypes().get(0);
    internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_BrokerTopicConfigMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yimq_common_protobuf_topic_BrokerTopicConfigWrapper_BrokerTopicConfigMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.yimq.common.topic.TopicConfigProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
