// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/route/TopicRouteData.proto

package com.yimq.common.protocol.route;

public final class TopicRouteDataProto {
  private TopicRouteDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopicRouteDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yimq.common.protobuf.route.TopicRouteData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string topic = 1;</code>
     */
    boolean hasTopic();
    /**
     * <code>required string topic = 1;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>required string topic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    java.util.List<com.yimq.common.protocol.route.BrokerDataProto.BrokerData> 
        getBrokerDatasList();
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    com.yimq.common.protocol.route.BrokerDataProto.BrokerData getBrokerDatas(int index);
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    int getBrokerDatasCount();
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    java.util.List<? extends com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder> 
        getBrokerDatasOrBuilderList();
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder getBrokerDatasOrBuilder(
        int index);

    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    java.util.List<com.yimq.common.protocol.route.QueueDataProto.QueueData> 
        getQueueDatasList();
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    com.yimq.common.protocol.route.QueueDataProto.QueueData getQueueDatas(int index);
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    int getQueueDatasCount();
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    java.util.List<? extends com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder> 
        getQueueDatasOrBuilderList();
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder getQueueDatasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.yimq.common.protobuf.route.TopicRouteData}
   */
  public  static final class TopicRouteData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yimq.common.protobuf.route.TopicRouteData)
      TopicRouteDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopicRouteData.newBuilder() to construct.
    private TopicRouteData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopicRouteData() {
      topic_ = "";
      brokerDatas_ = java.util.Collections.emptyList();
      queueDatas_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TopicRouteData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              topic_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                brokerDatas_ = new java.util.ArrayList<com.yimq.common.protocol.route.BrokerDataProto.BrokerData>();
                mutable_bitField0_ |= 0x00000002;
              }
              brokerDatas_.add(
                  input.readMessage(com.yimq.common.protocol.route.BrokerDataProto.BrokerData.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                queueDatas_ = new java.util.ArrayList<com.yimq.common.protocol.route.QueueDataProto.QueueData>();
                mutable_bitField0_ |= 0x00000004;
              }
              queueDatas_.add(
                  input.readMessage(com.yimq.common.protocol.route.QueueDataProto.QueueData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          brokerDatas_ = java.util.Collections.unmodifiableList(brokerDatas_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          queueDatas_ = java.util.Collections.unmodifiableList(queueDatas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData.class, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData.Builder.class);
    }

    private int bitField0_;
    public static final int TOPIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object topic_;
    /**
     * <code>required string topic = 1;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string topic = 1;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string topic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BROKERDATAS_FIELD_NUMBER = 2;
    private java.util.List<com.yimq.common.protocol.route.BrokerDataProto.BrokerData> brokerDatas_;
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    public java.util.List<com.yimq.common.protocol.route.BrokerDataProto.BrokerData> getBrokerDatasList() {
      return brokerDatas_;
    }
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    public java.util.List<? extends com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder> 
        getBrokerDatasOrBuilderList() {
      return brokerDatas_;
    }
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    public int getBrokerDatasCount() {
      return brokerDatas_.size();
    }
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    public com.yimq.common.protocol.route.BrokerDataProto.BrokerData getBrokerDatas(int index) {
      return brokerDatas_.get(index);
    }
    /**
     * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
     */
    public com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder getBrokerDatasOrBuilder(
        int index) {
      return brokerDatas_.get(index);
    }

    public static final int QUEUEDATAS_FIELD_NUMBER = 3;
    private java.util.List<com.yimq.common.protocol.route.QueueDataProto.QueueData> queueDatas_;
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    public java.util.List<com.yimq.common.protocol.route.QueueDataProto.QueueData> getQueueDatasList() {
      return queueDatas_;
    }
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    public java.util.List<? extends com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder> 
        getQueueDatasOrBuilderList() {
      return queueDatas_;
    }
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    public int getQueueDatasCount() {
      return queueDatas_.size();
    }
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    public com.yimq.common.protocol.route.QueueDataProto.QueueData getQueueDatas(int index) {
      return queueDatas_.get(index);
    }
    /**
     * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
     */
    public com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder getQueueDatasOrBuilder(
        int index) {
      return queueDatas_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getQueueDatasCount(); i++) {
        if (!getQueueDatas(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
      }
      for (int i = 0; i < brokerDatas_.size(); i++) {
        output.writeMessage(2, brokerDatas_.get(i));
      }
      for (int i = 0; i < queueDatas_.size(); i++) {
        output.writeMessage(3, queueDatas_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
      }
      for (int i = 0; i < brokerDatas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, brokerDatas_.get(i));
      }
      for (int i = 0; i < queueDatas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, queueDatas_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData)) {
        return super.equals(obj);
      }
      com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData other = (com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData) obj;

      boolean result = true;
      result = result && (hasTopic() == other.hasTopic());
      if (hasTopic()) {
        result = result && getTopic()
            .equals(other.getTopic());
      }
      result = result && getBrokerDatasList()
          .equals(other.getBrokerDatasList());
      result = result && getQueueDatasList()
          .equals(other.getQueueDatasList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTopic()) {
        hash = (37 * hash) + TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getTopic().hashCode();
      }
      if (getBrokerDatasCount() > 0) {
        hash = (37 * hash) + BROKERDATAS_FIELD_NUMBER;
        hash = (53 * hash) + getBrokerDatasList().hashCode();
      }
      if (getQueueDatasCount() > 0) {
        hash = (37 * hash) + QUEUEDATAS_FIELD_NUMBER;
        hash = (53 * hash) + getQueueDatasList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yimq.common.protobuf.route.TopicRouteData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yimq.common.protobuf.route.TopicRouteData)
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData.class, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData.Builder.class);
      }

      // Construct using com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBrokerDatasFieldBuilder();
          getQueueDatasFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (brokerDatasBuilder_ == null) {
          brokerDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          brokerDatasBuilder_.clear();
        }
        if (queueDatasBuilder_ == null) {
          queueDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          queueDatasBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteData_descriptor;
      }

      public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getDefaultInstanceForType() {
        return com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData.getDefaultInstance();
      }

      public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData build() {
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData buildPartial() {
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData result = new com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topic_ = topic_;
        if (brokerDatasBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            brokerDatas_ = java.util.Collections.unmodifiableList(brokerDatas_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.brokerDatas_ = brokerDatas_;
        } else {
          result.brokerDatas_ = brokerDatasBuilder_.build();
        }
        if (queueDatasBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            queueDatas_ = java.util.Collections.unmodifiableList(queueDatas_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.queueDatas_ = queueDatas_;
        } else {
          result.queueDatas_ = queueDatasBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData) {
          return mergeFrom((com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData other) {
        if (other == com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          bitField0_ |= 0x00000001;
          topic_ = other.topic_;
          onChanged();
        }
        if (brokerDatasBuilder_ == null) {
          if (!other.brokerDatas_.isEmpty()) {
            if (brokerDatas_.isEmpty()) {
              brokerDatas_ = other.brokerDatas_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBrokerDatasIsMutable();
              brokerDatas_.addAll(other.brokerDatas_);
            }
            onChanged();
          }
        } else {
          if (!other.brokerDatas_.isEmpty()) {
            if (brokerDatasBuilder_.isEmpty()) {
              brokerDatasBuilder_.dispose();
              brokerDatasBuilder_ = null;
              brokerDatas_ = other.brokerDatas_;
              bitField0_ = (bitField0_ & ~0x00000002);
              brokerDatasBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBrokerDatasFieldBuilder() : null;
            } else {
              brokerDatasBuilder_.addAllMessages(other.brokerDatas_);
            }
          }
        }
        if (queueDatasBuilder_ == null) {
          if (!other.queueDatas_.isEmpty()) {
            if (queueDatas_.isEmpty()) {
              queueDatas_ = other.queueDatas_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureQueueDatasIsMutable();
              queueDatas_.addAll(other.queueDatas_);
            }
            onChanged();
          }
        } else {
          if (!other.queueDatas_.isEmpty()) {
            if (queueDatasBuilder_.isEmpty()) {
              queueDatasBuilder_.dispose();
              queueDatasBuilder_ = null;
              queueDatas_ = other.queueDatas_;
              bitField0_ = (bitField0_ & ~0x00000004);
              queueDatasBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getQueueDatasFieldBuilder() : null;
            } else {
              queueDatasBuilder_.addAllMessages(other.queueDatas_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTopic()) {
          return false;
        }
        for (int i = 0; i < getQueueDatasCount(); i++) {
          if (!getQueueDatas(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object topic_ = "";
      /**
       * <code>required string topic = 1;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            topic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.yimq.common.protocol.route.BrokerDataProto.BrokerData> brokerDatas_ =
        java.util.Collections.emptyList();
      private void ensureBrokerDatasIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          brokerDatas_ = new java.util.ArrayList<com.yimq.common.protocol.route.BrokerDataProto.BrokerData>(brokerDatas_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yimq.common.protocol.route.BrokerDataProto.BrokerData, com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder, com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder> brokerDatasBuilder_;

      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public java.util.List<com.yimq.common.protocol.route.BrokerDataProto.BrokerData> getBrokerDatasList() {
        if (brokerDatasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(brokerDatas_);
        } else {
          return brokerDatasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public int getBrokerDatasCount() {
        if (brokerDatasBuilder_ == null) {
          return brokerDatas_.size();
        } else {
          return brokerDatasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public com.yimq.common.protocol.route.BrokerDataProto.BrokerData getBrokerDatas(int index) {
        if (brokerDatasBuilder_ == null) {
          return brokerDatas_.get(index);
        } else {
          return brokerDatasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder setBrokerDatas(
          int index, com.yimq.common.protocol.route.BrokerDataProto.BrokerData value) {
        if (brokerDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerDatasIsMutable();
          brokerDatas_.set(index, value);
          onChanged();
        } else {
          brokerDatasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder setBrokerDatas(
          int index, com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder builderForValue) {
        if (brokerDatasBuilder_ == null) {
          ensureBrokerDatasIsMutable();
          brokerDatas_.set(index, builderForValue.build());
          onChanged();
        } else {
          brokerDatasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder addBrokerDatas(com.yimq.common.protocol.route.BrokerDataProto.BrokerData value) {
        if (brokerDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerDatasIsMutable();
          brokerDatas_.add(value);
          onChanged();
        } else {
          brokerDatasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder addBrokerDatas(
          int index, com.yimq.common.protocol.route.BrokerDataProto.BrokerData value) {
        if (brokerDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerDatasIsMutable();
          brokerDatas_.add(index, value);
          onChanged();
        } else {
          brokerDatasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder addBrokerDatas(
          com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder builderForValue) {
        if (brokerDatasBuilder_ == null) {
          ensureBrokerDatasIsMutable();
          brokerDatas_.add(builderForValue.build());
          onChanged();
        } else {
          brokerDatasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder addBrokerDatas(
          int index, com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder builderForValue) {
        if (brokerDatasBuilder_ == null) {
          ensureBrokerDatasIsMutable();
          brokerDatas_.add(index, builderForValue.build());
          onChanged();
        } else {
          brokerDatasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder addAllBrokerDatas(
          java.lang.Iterable<? extends com.yimq.common.protocol.route.BrokerDataProto.BrokerData> values) {
        if (brokerDatasBuilder_ == null) {
          ensureBrokerDatasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, brokerDatas_);
          onChanged();
        } else {
          brokerDatasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder clearBrokerDatas() {
        if (brokerDatasBuilder_ == null) {
          brokerDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          brokerDatasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public Builder removeBrokerDatas(int index) {
        if (brokerDatasBuilder_ == null) {
          ensureBrokerDatasIsMutable();
          brokerDatas_.remove(index);
          onChanged();
        } else {
          brokerDatasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder getBrokerDatasBuilder(
          int index) {
        return getBrokerDatasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder getBrokerDatasOrBuilder(
          int index) {
        if (brokerDatasBuilder_ == null) {
          return brokerDatas_.get(index);  } else {
          return brokerDatasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public java.util.List<? extends com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder> 
           getBrokerDatasOrBuilderList() {
        if (brokerDatasBuilder_ != null) {
          return brokerDatasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(brokerDatas_);
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder addBrokerDatasBuilder() {
        return getBrokerDatasFieldBuilder().addBuilder(
            com.yimq.common.protocol.route.BrokerDataProto.BrokerData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder addBrokerDatasBuilder(
          int index) {
        return getBrokerDatasFieldBuilder().addBuilder(
            index, com.yimq.common.protocol.route.BrokerDataProto.BrokerData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.BrokerData brokerDatas = 2;</code>
       */
      public java.util.List<com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder> 
           getBrokerDatasBuilderList() {
        return getBrokerDatasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yimq.common.protocol.route.BrokerDataProto.BrokerData, com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder, com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder> 
          getBrokerDatasFieldBuilder() {
        if (brokerDatasBuilder_ == null) {
          brokerDatasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yimq.common.protocol.route.BrokerDataProto.BrokerData, com.yimq.common.protocol.route.BrokerDataProto.BrokerData.Builder, com.yimq.common.protocol.route.BrokerDataProto.BrokerDataOrBuilder>(
                  brokerDatas_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          brokerDatas_ = null;
        }
        return brokerDatasBuilder_;
      }

      private java.util.List<com.yimq.common.protocol.route.QueueDataProto.QueueData> queueDatas_ =
        java.util.Collections.emptyList();
      private void ensureQueueDatasIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          queueDatas_ = new java.util.ArrayList<com.yimq.common.protocol.route.QueueDataProto.QueueData>(queueDatas_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yimq.common.protocol.route.QueueDataProto.QueueData, com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder, com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder> queueDatasBuilder_;

      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public java.util.List<com.yimq.common.protocol.route.QueueDataProto.QueueData> getQueueDatasList() {
        if (queueDatasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(queueDatas_);
        } else {
          return queueDatasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public int getQueueDatasCount() {
        if (queueDatasBuilder_ == null) {
          return queueDatas_.size();
        } else {
          return queueDatasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public com.yimq.common.protocol.route.QueueDataProto.QueueData getQueueDatas(int index) {
        if (queueDatasBuilder_ == null) {
          return queueDatas_.get(index);
        } else {
          return queueDatasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder setQueueDatas(
          int index, com.yimq.common.protocol.route.QueueDataProto.QueueData value) {
        if (queueDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQueueDatasIsMutable();
          queueDatas_.set(index, value);
          onChanged();
        } else {
          queueDatasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder setQueueDatas(
          int index, com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder builderForValue) {
        if (queueDatasBuilder_ == null) {
          ensureQueueDatasIsMutable();
          queueDatas_.set(index, builderForValue.build());
          onChanged();
        } else {
          queueDatasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder addQueueDatas(com.yimq.common.protocol.route.QueueDataProto.QueueData value) {
        if (queueDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQueueDatasIsMutable();
          queueDatas_.add(value);
          onChanged();
        } else {
          queueDatasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder addQueueDatas(
          int index, com.yimq.common.protocol.route.QueueDataProto.QueueData value) {
        if (queueDatasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQueueDatasIsMutable();
          queueDatas_.add(index, value);
          onChanged();
        } else {
          queueDatasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder addQueueDatas(
          com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder builderForValue) {
        if (queueDatasBuilder_ == null) {
          ensureQueueDatasIsMutable();
          queueDatas_.add(builderForValue.build());
          onChanged();
        } else {
          queueDatasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder addQueueDatas(
          int index, com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder builderForValue) {
        if (queueDatasBuilder_ == null) {
          ensureQueueDatasIsMutable();
          queueDatas_.add(index, builderForValue.build());
          onChanged();
        } else {
          queueDatasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder addAllQueueDatas(
          java.lang.Iterable<? extends com.yimq.common.protocol.route.QueueDataProto.QueueData> values) {
        if (queueDatasBuilder_ == null) {
          ensureQueueDatasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, queueDatas_);
          onChanged();
        } else {
          queueDatasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder clearQueueDatas() {
        if (queueDatasBuilder_ == null) {
          queueDatas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          queueDatasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public Builder removeQueueDatas(int index) {
        if (queueDatasBuilder_ == null) {
          ensureQueueDatasIsMutable();
          queueDatas_.remove(index);
          onChanged();
        } else {
          queueDatasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder getQueueDatasBuilder(
          int index) {
        return getQueueDatasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder getQueueDatasOrBuilder(
          int index) {
        if (queueDatasBuilder_ == null) {
          return queueDatas_.get(index);  } else {
          return queueDatasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public java.util.List<? extends com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder> 
           getQueueDatasOrBuilderList() {
        if (queueDatasBuilder_ != null) {
          return queueDatasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(queueDatas_);
        }
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder addQueueDatasBuilder() {
        return getQueueDatasFieldBuilder().addBuilder(
            com.yimq.common.protocol.route.QueueDataProto.QueueData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder addQueueDatasBuilder(
          int index) {
        return getQueueDatasFieldBuilder().addBuilder(
            index, com.yimq.common.protocol.route.QueueDataProto.QueueData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.yimq.common.protobuf.route.QueueData queueDatas = 3;</code>
       */
      public java.util.List<com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder> 
           getQueueDatasBuilderList() {
        return getQueueDatasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.yimq.common.protocol.route.QueueDataProto.QueueData, com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder, com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder> 
          getQueueDatasFieldBuilder() {
        if (queueDatasBuilder_ == null) {
          queueDatasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.yimq.common.protocol.route.QueueDataProto.QueueData, com.yimq.common.protocol.route.QueueDataProto.QueueData.Builder, com.yimq.common.protocol.route.QueueDataProto.QueueDataOrBuilder>(
                  queueDatas_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          queueDatas_ = null;
        }
        return queueDatasBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yimq.common.protobuf.route.TopicRouteData)
    }

    // @@protoc_insertion_point(class_scope:com.yimq.common.protobuf.route.TopicRouteData)
    private static final com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData();
    }

    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TopicRouteData>
        PARSER = new com.google.protobuf.AbstractParser<TopicRouteData>() {
      public TopicRouteData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopicRouteData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TopicRouteData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopicRouteData> getParserForType() {
      return PARSER;
    }

    public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TopicRouteDataMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yimq.common.protobuf.route.TopicRouteDataMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */
    int getTopicRouteDataMapCount();
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */
    boolean containsTopicRouteDataMap(
        java.lang.String key);
    /**
     * Use {@link #getTopicRouteDataMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>
    getTopicRouteDataMap();
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */
    java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>
    getTopicRouteDataMapMap();
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */

    com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getTopicRouteDataMapOrDefault(
        java.lang.String key,
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData defaultValue);
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */

    com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getTopicRouteDataMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.yimq.common.protobuf.route.TopicRouteDataMap}
   */
  public  static final class TopicRouteDataMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yimq.common.protobuf.route.TopicRouteDataMap)
      TopicRouteDataMapOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopicRouteDataMap.newBuilder() to construct.
    private TopicRouteDataMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopicRouteDataMap() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TopicRouteDataMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                topicRouteDataMap_ = com.google.protobuf.MapField.newMapField(
                    TopicRouteDataMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>
              topicRouteDataMap__ = input.readMessage(
                  TopicRouteDataMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              topicRouteDataMap_.getMutableMap().put(
                  topicRouteDataMap__.getKey(), topicRouteDataMap__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetTopicRouteDataMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap.class, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap.Builder.class);
    }

    public static final int TOPICROUTEDATAMAP_FIELD_NUMBER = 1;
    private static final class TopicRouteDataMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>newDefaultInstance(
                  com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_TopicRouteDataMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> topicRouteDataMap_;
    private com.google.protobuf.MapField<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>
    internalGetTopicRouteDataMap() {
      if (topicRouteDataMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TopicRouteDataMapDefaultEntryHolder.defaultEntry);
      }
      return topicRouteDataMap_;
    }

    public int getTopicRouteDataMapCount() {
      return internalGetTopicRouteDataMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */

    public boolean containsTopicRouteDataMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTopicRouteDataMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTopicRouteDataMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> getTopicRouteDataMap() {
      return getTopicRouteDataMapMap();
    }
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */

    public java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> getTopicRouteDataMapMap() {
      return internalGetTopicRouteDataMap().getMap();
    }
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */

    public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getTopicRouteDataMapOrDefault(
        java.lang.String key,
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> map =
          internalGetTopicRouteDataMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
     */

    public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getTopicRouteDataMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> map =
          internalGetTopicRouteDataMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData item : getTopicRouteDataMapMap().values()) {
        if (!item.isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTopicRouteDataMap(),
          TopicRouteDataMapDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> entry
           : internalGetTopicRouteDataMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>
        topicRouteDataMap__ = TopicRouteDataMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, topicRouteDataMap__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap)) {
        return super.equals(obj);
      }
      com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap other = (com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap) obj;

      boolean result = true;
      result = result && internalGetTopicRouteDataMap().equals(
          other.internalGetTopicRouteDataMap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetTopicRouteDataMap().getMap().isEmpty()) {
        hash = (37 * hash) + TOPICROUTEDATAMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTopicRouteDataMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.yimq.common.protobuf.route.TopicRouteDataMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yimq.common.protobuf.route.TopicRouteDataMap)
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetTopicRouteDataMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableTopicRouteDataMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap.class, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap.Builder.class);
      }

      // Construct using com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableTopicRouteDataMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yimq.common.protocol.route.TopicRouteDataProto.internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_descriptor;
      }

      public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap getDefaultInstanceForType() {
        return com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap.getDefaultInstance();
      }

      public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap build() {
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap buildPartial() {
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap result = new com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap(this);
        int from_bitField0_ = bitField0_;
        result.topicRouteDataMap_ = internalGetTopicRouteDataMap();
        result.topicRouteDataMap_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap) {
          return mergeFrom((com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap other) {
        if (other == com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap.getDefaultInstance()) return this;
        internalGetMutableTopicRouteDataMap().mergeFrom(
            other.internalGetTopicRouteDataMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData item : getTopicRouteDataMapMap().values()) {
          if (!item.isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> topicRouteDataMap_;
      private com.google.protobuf.MapField<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>
      internalGetTopicRouteDataMap() {
        if (topicRouteDataMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TopicRouteDataMapDefaultEntryHolder.defaultEntry);
        }
        return topicRouteDataMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>
      internalGetMutableTopicRouteDataMap() {
        onChanged();;
        if (topicRouteDataMap_ == null) {
          topicRouteDataMap_ = com.google.protobuf.MapField.newMapField(
              TopicRouteDataMapDefaultEntryHolder.defaultEntry);
        }
        if (!topicRouteDataMap_.isMutable()) {
          topicRouteDataMap_ = topicRouteDataMap_.copy();
        }
        return topicRouteDataMap_;
      }

      public int getTopicRouteDataMapCount() {
        return internalGetTopicRouteDataMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
       */

      public boolean containsTopicRouteDataMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTopicRouteDataMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTopicRouteDataMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> getTopicRouteDataMap() {
        return getTopicRouteDataMapMap();
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
       */

      public java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> getTopicRouteDataMapMap() {
        return internalGetTopicRouteDataMap().getMap();
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
       */

      public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getTopicRouteDataMapOrDefault(
          java.lang.String key,
          com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> map =
            internalGetTopicRouteDataMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
       */

      public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData getTopicRouteDataMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> map =
            internalGetTopicRouteDataMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTopicRouteDataMap() {
        internalGetMutableTopicRouteDataMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
       */

      public Builder removeTopicRouteDataMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTopicRouteDataMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData>
      getMutableTopicRouteDataMap() {
        return internalGetMutableTopicRouteDataMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
       */
      public Builder putTopicRouteDataMap(
          java.lang.String key,
          com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTopicRouteDataMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.yimq.common.protobuf.route.TopicRouteData&gt; topicRouteDataMap = 1;</code>
       */

      public Builder putAllTopicRouteDataMap(
          java.util.Map<java.lang.String, com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteData> values) {
        internalGetMutableTopicRouteDataMap().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yimq.common.protobuf.route.TopicRouteDataMap)
    }

    // @@protoc_insertion_point(class_scope:com.yimq.common.protobuf.route.TopicRouteDataMap)
    private static final com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap();
    }

    public static com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TopicRouteDataMap>
        PARSER = new com.google.protobuf.AbstractParser<TopicRouteDataMap>() {
      public TopicRouteDataMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopicRouteDataMap(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TopicRouteDataMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopicRouteDataMap> getParserForType() {
      return PARSER;
    }

    public com.yimq.common.protocol.route.TopicRouteDataProto.TopicRouteDataMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yimq_common_protobuf_route_TopicRouteData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yimq_common_protobuf_route_TopicRouteData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_TopicRouteDataMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_TopicRouteDataMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src/protobuf/route/TopicRouteData.prot" +
      "o\022\036com.yimq.common.protobuf.route\032#src/p" +
      "rotobuf/route/BrokerData.proto\032\"src/prot" +
      "obuf/route/QueueData.proto\"\237\001\n\016TopicRout" +
      "eData\022\r\n\005topic\030\001 \002(\t\022?\n\013brokerDatas\030\002 \003(" +
      "\0132*.com.yimq.common.protobuf.route.Broke" +
      "rData\022=\n\nqueueDatas\030\003 \003(\0132).com.yimq.com" +
      "mon.protobuf.route.QueueData\"\342\001\n\021TopicRo" +
      "uteDataMap\022c\n\021topicRouteDataMap\030\001 \003(\0132H." +
      "com.yimq.common.protobuf.route.TopicRout" +
      "eDataMap.TopicRouteDataMapEntry\032h\n\026Topic" +
      "RouteDataMapEntry\022\013\n\003key\030\001 \001(\t\022=\n\005value\030" +
      "\002 \001(\0132..com.yimq.common.protobuf.route.T" +
      "opicRouteData:\0028\001B5\n\036com.yimq.common.pro" +
      "tocol.routeB\023TopicRouteDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.yimq.common.protocol.route.BrokerDataProto.getDescriptor(),
          com.yimq.common.protocol.route.QueueDataProto.getDescriptor(),
        }, assigner);
    internal_static_com_yimq_common_protobuf_route_TopicRouteData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yimq_common_protobuf_route_TopicRouteData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yimq_common_protobuf_route_TopicRouteData_descriptor,
        new java.lang.String[] { "Topic", "BrokerDatas", "QueueDatas", });
    internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_descriptor,
        new java.lang.String[] { "TopicRouteDataMap", });
    internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_TopicRouteDataMapEntry_descriptor =
      internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_descriptor.getNestedTypes().get(0);
    internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_TopicRouteDataMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yimq_common_protobuf_route_TopicRouteDataMap_TopicRouteDataMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.yimq.common.protocol.route.BrokerDataProto.getDescriptor();
    com.yimq.common.protocol.route.QueueDataProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
